name: Dependabot

# Trigger the workflow on pull requests, pushes to main, and manual dispatch
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          node-version: latest

  auto-merge:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Auto-merge PR
        uses: winstxnhdw/actions/.github/workflows/dependabot-public.yml@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          permissions:
            contents: write
