name: Dependabot

on: pull_request

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3

      - name: Install, build, and upload your site
        uses: withastro/action@v1
        with:
          node-version: latest

  auto-merge:
    needs: build
    uses: winstxnhdw/actions/.github/workflows/dependabot-public.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
